language: node_js
node_js:
    - "8"
    - "7"
    - "6"
    - "node"
install: npm install
before_script: npm install -g gulp-cli
script: 
    - npm test
after_success:
    - "git config user.name 'Travis CI - Tyrone'"
    - "git config user.email <new_overlord@yahoo.com>"
    - "git checkout master"
    - "git pull"
    - "npm test"
    - "git checkout origin integration"
    - "git merge master --no-ff --log"
    - "git push"
    - "git checkout master"

# blocklist
branches:
  except:
    - integration